version: "3.9"
services:
  gunicorn:
    build: .
    volumes:
      - ./db.sqlite3:/usr/src/app/db.sqlite3
      - ./maintenance_mode_state.txt:/usr/src/app/maintenance_mode_state.txt
    networks:
      - backend
  web:
    image: nginx
    depends_on:
      - "gunicorn"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/srv/public
    ports:
      - "0.0.0.0:8000:80/tcp"
    networks:
      - default
      - backend

networks:
  backend:
    driver: bridge
    internal: true